// Code generated by protoc-gen-go.
// source: ad_request.proto
// DO NOT EDIT!

/*
Package logger is a generated protocol buffer package.

It is generated from these files:
	ad_request.proto
	device.proto
	error.proto
	event.proto
	geoip.proto
	page.proto
	publisher.proto
	rpc.proto
	session.proto
	user.proto
	wurfl.proto

It has these top-level messages:
	AdRequest
	Device
	Error
	Event
	GeoIp
	Page
	Publisher
	Session
	User
	Wurfl
*/
package logger

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AdRequest struct {
}

func (m *AdRequest) Reset()                    { *m = AdRequest{} }
func (m *AdRequest) String() string            { return proto.CompactTextString(m) }
func (*AdRequest) ProtoMessage()               {}
func (*AdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*AdRequest)(nil), "logger.AdRequest")
}

func init() { proto.RegisterFile("ad_request.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 64 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x4c, 0x89, 0x2f,
	0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcb, 0xc9,
	0x4f, 0x4f, 0x4f, 0x2d, 0x52, 0xe2, 0xe6, 0xe2, 0x74, 0x4c, 0x09, 0x82, 0x48, 0x25, 0xb1, 0x81,
	0xe5, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xaf, 0x65, 0x85, 0x2f, 0x00, 0x00, 0x00,
}
