// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package logger is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Client
	IP
	User
	Pair
	Event
	Empty
	Error
*/
package logger

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event_Type int32

const (
	Event_BOOTLOADER_LOADED Event_Type = 0
	Event_DISCOVERY_LOADED  Event_Type = 1
	Event_SESSION_PING      Event_Type = 2
	Event_PAGE_VIEW         Event_Type = 3
	Event_IMPRESSION        Event_Type = 4
	Event_CLICK             Event_Type = 5
	Event_SKIP              Event_Type = 6
	Event_ON_SCREEN         Event_Type = 7
)

var Event_Type_name = map[int32]string{
	0: "BOOTLOADER_LOADED",
	1: "DISCOVERY_LOADED",
	2: "SESSION_PING",
	3: "PAGE_VIEW",
	4: "IMPRESSION",
	5: "CLICK",
	6: "SKIP",
	7: "ON_SCREEN",
}
var Event_Type_value = map[string]int32{
	"BOOTLOADER_LOADED": 0,
	"DISCOVERY_LOADED":  1,
	"SESSION_PING":      2,
	"PAGE_VIEW":         3,
	"IMPRESSION":        4,
	"CLICK":             5,
	"SKIP":              6,
	"ON_SCREEN":         7,
}

func (x Event_Type) String() string {
	return proto.EnumName(Event_Type_name, int32(x))
}
func (Event_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type Client struct {
	PID string `protobuf:"bytes,1,opt,name=pID" json:"pID,omitempty"`
	SID string `protobuf:"bytes,2,opt,name=sID" json:"sID,omitempty"`
}

func (m *Client) Reset()                    { *m = Client{} }
func (m *Client) String() string            { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()               {}
func (*Client) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type IP struct {
	V4 string `protobuf:"bytes,1,opt,name=v4" json:"v4,omitempty"`
	V6 string `protobuf:"bytes,2,opt,name=v6" json:"v6,omitempty"`
}

func (m *IP) Reset()                    { *m = IP{} }
func (m *IP) String() string            { return proto.CompactTextString(m) }
func (*IP) ProtoMessage()               {}
func (*IP) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type User struct {
	SessID       string      `protobuf:"bytes,1,opt,name=sessID" json:"sessID,omitempty"`
	Path         string      `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Adblocker    bool        `protobuf:"varint,3,opt,name=adblocker" json:"adblocker,omitempty"`
	UID          string      `protobuf:"bytes,4,opt,name=uID" json:"uID,omitempty"`
	PuID         string      `protobuf:"bytes,5,opt,name=puID" json:"puID,omitempty"`
	UserAgent    string      `protobuf:"bytes,6,opt,name=user_agent,json=userAgent" json:"user_agent,omitempty"`
	Device       string      `protobuf:"bytes,7,opt,name=device" json:"device,omitempty"`
	Domain       string      `protobuf:"bytes,8,opt,name=domain" json:"domain,omitempty"`
	PageLoadTime uint64      `protobuf:"varint,9,opt,name=page_load_time,json=pageLoadTime" json:"page_load_time,omitempty"`
	Location     *User_GeoIP `protobuf:"bytes,10,opt,name=location" json:"location,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *User) GetLocation() *User_GeoIP {
	if m != nil {
		return m.Location
	}
	return nil
}

type User_GeoIP struct {
	IP         *IP             `protobuf:"bytes,1,opt,name=IP,json=iP" json:"IP,omitempty"`
	Country    string          `protobuf:"bytes,2,opt,name=country" json:"country,omitempty"`
	City       string          `protobuf:"bytes,3,opt,name=city" json:"city,omitempty"`
	PostalCode string          `protobuf:"bytes,4,opt,name=postal_code,json=postalCode" json:"postal_code,omitempty"`
	TimeZone   string          `protobuf:"bytes,5,opt,name=time_zone,json=timeZone" json:"time_zone,omitempty"`
	MetroCode  uint32          `protobuf:"varint,6,opt,name=metro_code,json=metroCode" json:"metro_code,omitempty"`
	Isp        *User_GeoIP_ISP `protobuf:"bytes,7,opt,name=isp" json:"isp,omitempty"`
}

func (m *User_GeoIP) Reset()                    { *m = User_GeoIP{} }
func (m *User_GeoIP) String() string            { return proto.CompactTextString(m) }
func (*User_GeoIP) ProtoMessage()               {}
func (*User_GeoIP) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *User_GeoIP) GetIP() *IP {
	if m != nil {
		return m.IP
	}
	return nil
}

func (m *User_GeoIP) GetIsp() *User_GeoIP_ISP {
	if m != nil {
		return m.Isp
	}
	return nil
}

type User_GeoIP_ISP struct {
	AutonomousSystemNumber       uint32 `protobuf:"varint,1,opt,name=autonomous_system_number,json=autonomousSystemNumber" json:"autonomous_system_number,omitempty"`
	AutonomousSystemOrganization string `protobuf:"bytes,2,opt,name=autonomous_system_organization,json=autonomousSystemOrganization" json:"autonomous_system_organization,omitempty"`
	Isp                          string `protobuf:"bytes,3,opt,name=isp" json:"isp,omitempty"`
	Organization                 string `protobuf:"bytes,4,opt,name=organization" json:"organization,omitempty"`
}

func (m *User_GeoIP_ISP) Reset()                    { *m = User_GeoIP_ISP{} }
func (m *User_GeoIP_ISP) String() string            { return proto.CompactTextString(m) }
func (*User_GeoIP_ISP) ProtoMessage()               {}
func (*User_GeoIP_ISP) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0, 0} }

type Pair struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Pair) Reset()                    { *m = Pair{} }
func (m *Pair) String() string            { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()               {}
func (*Pair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Event struct {
	Type   Event_Type `protobuf:"varint,1,opt,name=type,enum=logger.Event_Type" json:"type,omitempty"`
	Client *Client    `protobuf:"bytes,2,opt,name=client" json:"client,omitempty"`
	User   *User      `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	Custom []*Pair    `protobuf:"bytes,4,rep,name=custom" json:"custom,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Event) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *Event) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Event) GetCustom() []*Pair {
	if m != nil {
		return m.Custom
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Error struct {
	ErrorCode uint32  `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	Client    *Client `protobuf:"bytes,2,opt,name=client" json:"client,omitempty"`
	User      *User   `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	Custom    []*Pair `protobuf:"bytes,4,rep,name=custom" json:"custom,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Error) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *Error) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Error) GetCustom() []*Pair {
	if m != nil {
		return m.Custom
	}
	return nil
}

func init() {
	proto.RegisterType((*Client)(nil), "logger.Client")
	proto.RegisterType((*IP)(nil), "logger.IP")
	proto.RegisterType((*User)(nil), "logger.User")
	proto.RegisterType((*User_GeoIP)(nil), "logger.User.GeoIP")
	proto.RegisterType((*User_GeoIP_ISP)(nil), "logger.User.GeoIP.ISP")
	proto.RegisterType((*Pair)(nil), "logger.Pair")
	proto.RegisterType((*Event)(nil), "logger.Event")
	proto.RegisterType((*Empty)(nil), "logger.Empty")
	proto.RegisterType((*Error)(nil), "logger.Error")
	proto.RegisterEnum("logger.Event_Type", Event_Type_name, Event_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Logger service

type LoggerClient interface {
	LogEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Empty, error)
	LogError(ctx context.Context, in *Error, opts ...grpc.CallOption) (*Empty, error)
}

type loggerClient struct {
	cc *grpc.ClientConn
}

func NewLoggerClient(cc *grpc.ClientConn) LoggerClient {
	return &loggerClient{cc}
}

func (c *loggerClient) LogEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/logger.Logger/LogEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) LogError(ctx context.Context, in *Error, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/logger.Logger/LogError", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Logger service

type LoggerServer interface {
	LogEvent(context.Context, *Event) (*Empty, error)
	LogError(context.Context, *Error) (*Empty, error)
}

func RegisterLoggerServer(s *grpc.Server, srv LoggerServer) {
	s.RegisterService(&_Logger_serviceDesc, srv)
}

func _Logger_LogEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).LogEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logger.Logger/LogEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).LogEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_LogError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Error)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).LogError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logger.Logger/LogError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).LogError(ctx, req.(*Error))
	}
	return interceptor(ctx, in, info, handler)
}

var _Logger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "logger.Logger",
	HandlerType: (*LoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogEvent",
			Handler:    _Logger_LogEvent_Handler,
		},
		{
			MethodName: "LogError",
			Handler:    _Logger_LogError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 737 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x54, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0x6e, 0x12, 0xc7, 0x89, 0x27, 0x3f, 0xf2, 0x59, 0x9d, 0x53, 0x59, 0x39, 0x3d, 0x87, 0xca,
	0xaa, 0x50, 0x85, 0x90, 0x2f, 0x02, 0x42, 0xdc, 0x96, 0xc4, 0xaa, 0xac, 0x86, 0xc4, 0xb2, 0x4b,
	0x11, 0xdc, 0x18, 0xd7, 0x59, 0x05, 0xab, 0xb1, 0xd7, 0xf2, 0x4f, 0xa4, 0xf4, 0x09, 0x78, 0x82,
	0x3e, 0x04, 0xd7, 0xdc, 0xf1, 0x72, 0xcc, 0xee, 0x3a, 0x4d, 0x4b, 0xef, 0xb9, 0xca, 0xcc, 0xf7,
	0xcd, 0x8c, 0xf7, 0xfb, 0x76, 0x36, 0x30, 0x28, 0x68, 0xbe, 0x89, 0x23, 0x6a, 0x65, 0x39, 0x2b,
	0x19, 0x51, 0xd7, 0x6c, 0xb5, 0xa2, 0xb9, 0xf9, 0x12, 0xd4, 0xc9, 0x3a, 0xa6, 0x69, 0x49, 0x74,
	0x68, 0x65, 0xce, 0xd4, 0x68, 0x1c, 0x37, 0x4e, 0x35, 0x8f, 0x87, 0x1c, 0x29, 0x10, 0x69, 0x4a,
	0x04, 0x43, 0xf3, 0x04, 0x9a, 0x8e, 0x4b, 0x86, 0xd0, 0xdc, 0xbc, 0xae, 0x0b, 0x31, 0x12, 0xf9,
	0x9b, 0xba, 0x0c, 0x23, 0xf3, 0x47, 0x1b, 0x94, 0x0f, 0xf8, 0x39, 0x72, 0x08, 0x6a, 0x41, 0x8b,
	0xe2, 0x7e, 0x6a, 0x9d, 0x11, 0x02, 0x4a, 0x16, 0x96, 0x5f, 0xeb, 0x16, 0x11, 0x93, 0x23, 0xd0,
	0xc2, 0xe5, 0xf5, 0x9a, 0x45, 0x37, 0x34, 0x37, 0x5a, 0x48, 0x74, 0xbd, 0x3d, 0xc0, 0x8f, 0x52,
	0xe1, 0x18, 0x45, 0x1e, 0xa5, 0xaa, 0x67, 0x70, 0xa8, 0x5d, 0xcf, 0xe0, 0xd8, 0x7f, 0x00, 0x15,
	0x7e, 0x37, 0x08, 0x57, 0x28, 0xc8, 0x50, 0x05, 0xa3, 0x71, 0xe4, 0x8c, 0x03, 0xfc, 0x38, 0x4b,
	0xca, 0x3d, 0x30, 0x3a, 0xf2, 0x38, 0x32, 0x13, 0x38, 0x4b, 0xc2, 0x38, 0x35, 0xba, 0x35, 0x2e,
	0x32, 0x72, 0x02, 0xc3, 0x0c, 0x47, 0x05, 0x6b, 0x16, 0x2e, 0x83, 0x32, 0x4e, 0xa8, 0xa1, 0x21,
	0xaf, 0x78, 0x7d, 0x8e, 0xce, 0x10, 0xbc, 0x44, 0x8c, 0x58, 0xd0, 0xc5, 0x43, 0x86, 0x65, 0xcc,
	0x52, 0x03, 0x90, 0xef, 0x8d, 0x89, 0x25, 0xcd, 0xb5, 0xb8, 0x09, 0xd6, 0x39, 0x65, 0x8e, 0xeb,
	0xdd, 0xd7, 0x8c, 0xee, 0x5a, 0xd0, 0x16, 0x18, 0x19, 0x71, 0x37, 0x85, 0x35, 0xbd, 0x31, 0xec,
	0x7a, 0xb0, 0xb6, 0x19, 0xbb, 0xc4, 0x80, 0x4e, 0xc4, 0xaa, 0xb4, 0xcc, 0xb7, 0xb5, 0x4b, 0xbb,
	0x94, 0x0b, 0x8f, 0xe2, 0x72, 0x2b, 0x3c, 0x42, 0xe1, 0x3c, 0x26, 0xcf, 0xa0, 0x97, 0xb1, 0xa2,
	0x0c, 0xd7, 0x41, 0xc4, 0x96, 0xb4, 0xb6, 0x09, 0x24, 0x34, 0x41, 0x84, 0xfc, 0x0b, 0x1a, 0x17,
	0x10, 0xdc, 0xb2, 0x94, 0xd6, 0x96, 0x75, 0x39, 0xf0, 0x19, 0x73, 0x6e, 0x5b, 0x42, 0xcb, 0x9c,
	0xc9, 0x66, 0x6e, 0xdb, 0xc0, 0xd3, 0x04, 0x22, 0x7a, 0x4f, 0xa1, 0x15, 0x17, 0x99, 0xf0, 0xac,
	0x37, 0x3e, 0x7c, 0xaa, 0xcd, 0x72, 0x7c, 0xd7, 0xe3, 0x25, 0xa3, 0x9f, 0x0d, 0x68, 0x61, 0x42,
	0xde, 0x82, 0x11, 0x56, 0x25, 0x4b, 0x59, 0xc2, 0xaa, 0x22, 0x28, 0xb6, 0x45, 0x49, 0x93, 0x20,
	0xad, 0x92, 0x6b, 0xbc, 0xda, 0x86, 0x18, 0x7f, 0xb8, 0xe7, 0x7d, 0x41, 0xcf, 0x05, 0x4b, 0xa6,
	0xf0, 0xff, 0xd3, 0x4e, 0x96, 0xaf, 0xc2, 0x34, 0xbe, 0x95, 0x16, 0x4b, 0x37, 0x8e, 0x7e, 0xef,
	0x5f, 0x3c, 0xa8, 0xe1, 0xdb, 0xc2, 0x4f, 0x2c, 0x1d, 0xe2, 0x21, 0x31, 0xa1, 0xff, 0x68, 0x8a,
	0x74, 0xe8, 0x11, 0x66, 0x5a, 0xa0, 0xb8, 0x61, 0x2c, 0x76, 0xed, 0x86, 0x6e, 0x77, 0x0f, 0x01,
	0x43, 0xf2, 0x37, 0xb4, 0x37, 0xe1, 0xba, 0xa2, 0xf5, 0xc7, 0x65, 0x62, 0x7e, 0x6f, 0x42, 0xdb,
	0xde, 0xf0, 0xc5, 0x7a, 0x0e, 0x4a, 0xb9, 0xcd, 0xa8, 0x68, 0x19, 0xee, 0xaf, 0x5f, 0x90, 0xd6,
	0x25, 0x32, 0x9e, 0xe0, 0xb1, 0x4e, 0x8d, 0xc4, 0x63, 0x13, 0x83, 0x7a, 0xe3, 0xe1, 0xae, 0x52,
	0x3e, 0x41, 0xaf, 0x66, 0xc9, 0x31, 0x28, 0x7c, 0x6b, 0x85, 0x80, 0xde, 0xb8, 0xff, 0xd0, 0x72,
	0x4f, 0x30, 0xb8, 0x9a, 0x6a, 0x54, 0x15, 0x25, 0x4b, 0x50, 0x49, 0xeb, 0x61, 0x0d, 0x57, 0xe0,
	0xd5, 0x9c, 0xf9, 0xad, 0x01, 0x0a, 0xff, 0x3c, 0xf9, 0x07, 0xfe, 0x7a, 0xb7, 0x58, 0x5c, 0xce,
	0x16, 0x67, 0x53, 0xdb, 0x0b, 0xc4, 0xcf, 0x54, 0x3f, 0x40, 0x5d, 0xfa, 0xd4, 0xf1, 0x27, 0x8b,
	0x2b, 0xdb, 0xfb, 0xb4, 0x43, 0x1b, 0xa8, 0xbf, 0xef, 0xdb, 0xbe, 0xef, 0x2c, 0xe6, 0x81, 0xeb,
	0xcc, 0xcf, 0xf5, 0x26, 0x19, 0x80, 0xe6, 0x9e, 0x9d, 0xdb, 0xc1, 0x95, 0x63, 0x7f, 0xd4, 0x5b,
	0xf8, 0xde, 0xc1, 0x79, 0xef, 0x7a, 0xb2, 0x46, 0x57, 0x88, 0x06, 0xed, 0xc9, 0xcc, 0x99, 0x5c,
	0xe8, 0x6d, 0xd2, 0x05, 0xc5, 0xbf, 0x70, 0x5c, 0x5d, 0xe5, 0x3d, 0x38, 0xc0, 0x9f, 0x78, 0xb6,
	0x3d, 0xd7, 0x3b, 0x66, 0x07, 0xbd, 0x4a, 0xb2, 0x72, 0x6b, 0xde, 0x35, 0x30, 0xca, 0x73, 0x96,
	0xf3, 0xb5, 0xa3, 0x3c, 0x90, 0x6b, 0x27, 0xf7, 0x42, 0x13, 0x88, 0x58, 0xbb, 0x3f, 0x6c, 0xd6,
	0xf8, 0x0b, 0xa8, 0x33, 0x01, 0x93, 0x17, 0xd0, 0xc5, 0x48, 0x5e, 0xed, 0xe0, 0xd1, 0x65, 0x8e,
	0xf6, 0xa9, 0x10, 0x73, 0xb0, 0xab, 0x15, 0x82, 0xf6, 0x24, 0x4f, 0x9f, 0xd4, 0x5e, 0xab, 0xe2,
	0xaf, 0xf7, 0xd5, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x1b, 0xe0, 0x8e, 0x8b, 0x05, 0x00,
	0x00,
}
