// Code generated by protoc-gen-go.
// source: subscription.proto
// DO NOT EDIT!

package logger

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Subscription includes the details of this publisher's subscription.
type Subscription struct {
}

func (m *Subscription) Reset()                    { *m = Subscription{} }
func (m *Subscription) String() string            { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()               {}
func (*Subscription) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

func init() {
	proto.RegisterType((*Subscription)(nil), "logger.Subscription")
}

func init() { proto.RegisterFile("subscription.proto", fileDescriptor9) }

var fileDescriptor9 = []byte{
	// 64 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x2e, 0x4d, 0x2a,
	0x4e, 0x2e, 0xca, 0x2c, 0x28, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0xcb, 0xc9, 0x4f, 0x4f, 0x4f, 0x2d, 0x52, 0xe2, 0xe3, 0xe2, 0x09, 0x46, 0x92, 0x4d, 0x62, 0x03,
	0x4b, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x63, 0x17, 0x78, 0x34, 0x00, 0x00, 0x00,
}
