// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.publica.storm.s3.proto;

/**
 * Protobuf type {@code logger.Client}
 */
public  final class Client extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:logger.Client)
    ClientOrBuilder {
  // Use Client.newBuilder() to construct.
  private Client(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Client() {
    pID_ = "";
    sID_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Client(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            pID_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            sID_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_Client_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_Client_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.publica.storm.s3.proto.Client.class, com.publica.storm.s3.proto.Client.Builder.class);
  }

  public static final int PID_FIELD_NUMBER = 1;
  private volatile java.lang.Object pID_;
  /**
   * <code>optional string pID = 1;</code>
   */
  public java.lang.String getPID() {
    java.lang.Object ref = pID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pID_ = s;
      return s;
    }
  }
  /**
   * <code>optional string pID = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPIDBytes() {
    java.lang.Object ref = pID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SID_FIELD_NUMBER = 2;
  private volatile java.lang.Object sID_;
  /**
   * <code>optional string sID = 2;</code>
   */
  public java.lang.String getSID() {
    java.lang.Object ref = sID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sID_ = s;
      return s;
    }
  }
  /**
   * <code>optional string sID = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSIDBytes() {
    java.lang.Object ref = sID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, pID_);
    }
    if (!getSIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, sID_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, pID_);
    }
    if (!getSIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, sID_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.publica.storm.s3.proto.Client)) {
      return super.equals(obj);
    }
    com.publica.storm.s3.proto.Client other = (com.publica.storm.s3.proto.Client) obj;

    boolean result = true;
    result = result && getPID()
        .equals(other.getPID());
    result = result && getSID()
        .equals(other.getSID());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + PID_FIELD_NUMBER;
    hash = (53 * hash) + getPID().hashCode();
    hash = (37 * hash) + SID_FIELD_NUMBER;
    hash = (53 * hash) + getSID().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.publica.storm.s3.proto.Client parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.publica.storm.s3.proto.Client parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.publica.storm.s3.proto.Client parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.publica.storm.s3.proto.Client parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.publica.storm.s3.proto.Client parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.publica.storm.s3.proto.Client parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.publica.storm.s3.proto.Client parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.publica.storm.s3.proto.Client parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.publica.storm.s3.proto.Client parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.publica.storm.s3.proto.Client parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.publica.storm.s3.proto.Client prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code logger.Client}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:logger.Client)
      com.publica.storm.s3.proto.ClientOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_Client_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_Client_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.publica.storm.s3.proto.Client.class, com.publica.storm.s3.proto.Client.Builder.class);
    }

    // Construct using com.publica.storm.s3.proto.Client.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      pID_ = "";

      sID_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_Client_descriptor;
    }

    public com.publica.storm.s3.proto.Client getDefaultInstanceForType() {
      return com.publica.storm.s3.proto.Client.getDefaultInstance();
    }

    public com.publica.storm.s3.proto.Client build() {
      com.publica.storm.s3.proto.Client result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.publica.storm.s3.proto.Client buildPartial() {
      com.publica.storm.s3.proto.Client result = new com.publica.storm.s3.proto.Client(this);
      result.pID_ = pID_;
      result.sID_ = sID_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.publica.storm.s3.proto.Client) {
        return mergeFrom((com.publica.storm.s3.proto.Client)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.publica.storm.s3.proto.Client other) {
      if (other == com.publica.storm.s3.proto.Client.getDefaultInstance()) return this;
      if (!other.getPID().isEmpty()) {
        pID_ = other.pID_;
        onChanged();
      }
      if (!other.getSID().isEmpty()) {
        sID_ = other.sID_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.publica.storm.s3.proto.Client parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.publica.storm.s3.proto.Client) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object pID_ = "";
    /**
     * <code>optional string pID = 1;</code>
     */
    public java.lang.String getPID() {
      java.lang.Object ref = pID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string pID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPIDBytes() {
      java.lang.Object ref = pID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string pID = 1;</code>
     */
    public Builder setPID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string pID = 1;</code>
     */
    public Builder clearPID() {
      
      pID_ = getDefaultInstance().getPID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string pID = 1;</code>
     */
    public Builder setPIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sID_ = "";
    /**
     * <code>optional string sID = 2;</code>
     */
    public java.lang.String getSID() {
      java.lang.Object ref = sID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSIDBytes() {
      java.lang.Object ref = sID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sID = 2;</code>
     */
    public Builder setSID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sID = 2;</code>
     */
    public Builder clearSID() {
      
      sID_ = getDefaultInstance().getSID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sID = 2;</code>
     */
    public Builder setSIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sID_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:logger.Client)
  }

  // @@protoc_insertion_point(class_scope:logger.Client)
  private static final com.publica.storm.s3.proto.Client DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.publica.storm.s3.proto.Client();
  }

  public static com.publica.storm.s3.proto.Client getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Client>
      PARSER = new com.google.protobuf.AbstractParser<Client>() {
    public Client parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Client(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Client> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Client> getParserForType() {
    return PARSER;
  }

  public com.publica.storm.s3.proto.Client getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

