// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.publica.storm.s3.proto;

public interface ClientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:logger.Client)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string pID = 1;</code>
   */
  java.lang.String getPID();
  /**
   * <code>optional string pID = 1;</code>
   */
  com.google.protobuf.ByteString
      getPIDBytes();

  /**
   * <code>optional string sID = 2;</code>
   */
  java.lang.String getSID();
  /**
   * <code>optional string sID = 2;</code>
   */
  com.google.protobuf.ByteString
      getSIDBytes();
}
