// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.publica.storm.s3.proto;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:logger.Empty)
    com.google.protobuf.MessageOrBuilder {
}
