// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.publica.storm.s3.proto;

/**
 * Protobuf type {@code logger.Error}
 */
public  final class Error extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:logger.Error)
    ErrorOrBuilder {
  // Use Error.newBuilder() to construct.
  private Error(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Error() {
    errorCode_ = 0;
    custom_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Error(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            errorCode_ = input.readUInt32();
            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timestamp_ != null) {
              subBuilder = timestamp_.toBuilder();
            }
            timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timestamp_);
              timestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.publica.storm.s3.proto.Client.Builder subBuilder = null;
            if (client_ != null) {
              subBuilder = client_.toBuilder();
            }
            client_ = input.readMessage(com.publica.storm.s3.proto.Client.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(client_);
              client_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.publica.storm.s3.proto.User.Builder subBuilder = null;
            if (user_ != null) {
              subBuilder = user_.toBuilder();
            }
            user_ = input.readMessage(com.publica.storm.s3.proto.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(user_);
              user_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              custom_ = new java.util.ArrayList<com.publica.storm.s3.proto.Pair>();
              mutable_bitField0_ |= 0x00000010;
            }
            custom_.add(input.readMessage(com.publica.storm.s3.proto.Pair.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        custom_ = java.util.Collections.unmodifiableList(custom_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_Error_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_Error_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.publica.storm.s3.proto.Error.class, com.publica.storm.s3.proto.Error.Builder.class);
  }

  private int bitField0_;
  public static final int ERROR_CODE_FIELD_NUMBER = 1;
  private int errorCode_;
  /**
   * <code>optional uint32 error_code = 1;</code>
   */
  public int getErrorCode() {
    return errorCode_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <code>optional .google.protobuf.Timestamp timestamp = 2;</code>
   */
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <code>optional .google.protobuf.Timestamp timestamp = 2;</code>
   */
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>optional .google.protobuf.Timestamp timestamp = 2;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return getTimestamp();
  }

  public static final int CLIENT_FIELD_NUMBER = 3;
  private com.publica.storm.s3.proto.Client client_;
  /**
   * <code>optional .logger.Client client = 3;</code>
   */
  public boolean hasClient() {
    return client_ != null;
  }
  /**
   * <code>optional .logger.Client client = 3;</code>
   */
  public com.publica.storm.s3.proto.Client getClient() {
    return client_ == null ? com.publica.storm.s3.proto.Client.getDefaultInstance() : client_;
  }
  /**
   * <code>optional .logger.Client client = 3;</code>
   */
  public com.publica.storm.s3.proto.ClientOrBuilder getClientOrBuilder() {
    return getClient();
  }

  public static final int USER_FIELD_NUMBER = 4;
  private com.publica.storm.s3.proto.User user_;
  /**
   * <code>optional .logger.User user = 4;</code>
   */
  public boolean hasUser() {
    return user_ != null;
  }
  /**
   * <code>optional .logger.User user = 4;</code>
   */
  public com.publica.storm.s3.proto.User getUser() {
    return user_ == null ? com.publica.storm.s3.proto.User.getDefaultInstance() : user_;
  }
  /**
   * <code>optional .logger.User user = 4;</code>
   */
  public com.publica.storm.s3.proto.UserOrBuilder getUserOrBuilder() {
    return getUser();
  }

  public static final int CUSTOM_FIELD_NUMBER = 5;
  private java.util.List<com.publica.storm.s3.proto.Pair> custom_;
  /**
   * <code>repeated .logger.Pair custom = 5;</code>
   */
  public java.util.List<com.publica.storm.s3.proto.Pair> getCustomList() {
    return custom_;
  }
  /**
   * <code>repeated .logger.Pair custom = 5;</code>
   */
  public java.util.List<? extends com.publica.storm.s3.proto.PairOrBuilder> 
      getCustomOrBuilderList() {
    return custom_;
  }
  /**
   * <code>repeated .logger.Pair custom = 5;</code>
   */
  public int getCustomCount() {
    return custom_.size();
  }
  /**
   * <code>repeated .logger.Pair custom = 5;</code>
   */
  public com.publica.storm.s3.proto.Pair getCustom(int index) {
    return custom_.get(index);
  }
  /**
   * <code>repeated .logger.Pair custom = 5;</code>
   */
  public com.publica.storm.s3.proto.PairOrBuilder getCustomOrBuilder(
      int index) {
    return custom_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (errorCode_ != 0) {
      output.writeUInt32(1, errorCode_);
    }
    if (timestamp_ != null) {
      output.writeMessage(2, getTimestamp());
    }
    if (client_ != null) {
      output.writeMessage(3, getClient());
    }
    if (user_ != null) {
      output.writeMessage(4, getUser());
    }
    for (int i = 0; i < custom_.size(); i++) {
      output.writeMessage(5, custom_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (errorCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, errorCode_);
    }
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTimestamp());
    }
    if (client_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getClient());
    }
    if (user_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getUser());
    }
    for (int i = 0; i < custom_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, custom_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.publica.storm.s3.proto.Error)) {
      return super.equals(obj);
    }
    com.publica.storm.s3.proto.Error other = (com.publica.storm.s3.proto.Error) obj;

    boolean result = true;
    result = result && (getErrorCode()
        == other.getErrorCode());
    result = result && (hasTimestamp() == other.hasTimestamp());
    if (hasTimestamp()) {
      result = result && getTimestamp()
          .equals(other.getTimestamp());
    }
    result = result && (hasClient() == other.hasClient());
    if (hasClient()) {
      result = result && getClient()
          .equals(other.getClient());
    }
    result = result && (hasUser() == other.hasUser());
    if (hasUser()) {
      result = result && getUser()
          .equals(other.getUser());
    }
    result = result && getCustomList()
        .equals(other.getCustomList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ERROR_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorCode();
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    if (hasClient()) {
      hash = (37 * hash) + CLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getClient().hashCode();
    }
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    if (getCustomCount() > 0) {
      hash = (37 * hash) + CUSTOM_FIELD_NUMBER;
      hash = (53 * hash) + getCustomList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.publica.storm.s3.proto.Error parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.publica.storm.s3.proto.Error parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.publica.storm.s3.proto.Error parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.publica.storm.s3.proto.Error parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.publica.storm.s3.proto.Error parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.publica.storm.s3.proto.Error parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.publica.storm.s3.proto.Error parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.publica.storm.s3.proto.Error parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.publica.storm.s3.proto.Error parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.publica.storm.s3.proto.Error parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.publica.storm.s3.proto.Error prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code logger.Error}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:logger.Error)
      com.publica.storm.s3.proto.ErrorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_Error_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_Error_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.publica.storm.s3.proto.Error.class, com.publica.storm.s3.proto.Error.Builder.class);
    }

    // Construct using com.publica.storm.s3.proto.Error.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getCustomFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      errorCode_ = 0;

      if (timestampBuilder_ == null) {
        timestamp_ = null;
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }
      if (clientBuilder_ == null) {
        client_ = null;
      } else {
        client_ = null;
        clientBuilder_ = null;
      }
      if (userBuilder_ == null) {
        user_ = null;
      } else {
        user_ = null;
        userBuilder_ = null;
      }
      if (customBuilder_ == null) {
        custom_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        customBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_Error_descriptor;
    }

    public com.publica.storm.s3.proto.Error getDefaultInstanceForType() {
      return com.publica.storm.s3.proto.Error.getDefaultInstance();
    }

    public com.publica.storm.s3.proto.Error build() {
      com.publica.storm.s3.proto.Error result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.publica.storm.s3.proto.Error buildPartial() {
      com.publica.storm.s3.proto.Error result = new com.publica.storm.s3.proto.Error(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.errorCode_ = errorCode_;
      if (timestampBuilder_ == null) {
        result.timestamp_ = timestamp_;
      } else {
        result.timestamp_ = timestampBuilder_.build();
      }
      if (clientBuilder_ == null) {
        result.client_ = client_;
      } else {
        result.client_ = clientBuilder_.build();
      }
      if (userBuilder_ == null) {
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      if (customBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          custom_ = java.util.Collections.unmodifiableList(custom_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.custom_ = custom_;
      } else {
        result.custom_ = customBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.publica.storm.s3.proto.Error) {
        return mergeFrom((com.publica.storm.s3.proto.Error)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.publica.storm.s3.proto.Error other) {
      if (other == com.publica.storm.s3.proto.Error.getDefaultInstance()) return this;
      if (other.getErrorCode() != 0) {
        setErrorCode(other.getErrorCode());
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (other.hasClient()) {
        mergeClient(other.getClient());
      }
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      if (customBuilder_ == null) {
        if (!other.custom_.isEmpty()) {
          if (custom_.isEmpty()) {
            custom_ = other.custom_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureCustomIsMutable();
            custom_.addAll(other.custom_);
          }
          onChanged();
        }
      } else {
        if (!other.custom_.isEmpty()) {
          if (customBuilder_.isEmpty()) {
            customBuilder_.dispose();
            customBuilder_ = null;
            custom_ = other.custom_;
            bitField0_ = (bitField0_ & ~0x00000010);
            customBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getCustomFieldBuilder() : null;
          } else {
            customBuilder_.addAllMessages(other.custom_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.publica.storm.s3.proto.Error parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.publica.storm.s3.proto.Error) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int errorCode_ ;
    /**
     * <code>optional uint32 error_code = 1;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }
    /**
     * <code>optional uint32 error_code = 1;</code>
     */
    public Builder setErrorCode(int value) {
      
      errorCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 error_code = 1;</code>
     */
    public Builder clearErrorCode() {
      
      errorCode_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp timestamp_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 2;</code>
     */
    public boolean hasTimestamp() {
      return timestampBuilder_ != null || timestamp_ != null;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 2;</code>
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 2;</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 2;</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 2;</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (timestamp_ != null) {
          timestamp_ =
            com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
        } else {
          timestamp_ = value;
        }
        onChanged();
      } else {
        timestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 2;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        timestamp_ = null;
        onChanged();
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private com.publica.storm.s3.proto.Client client_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.publica.storm.s3.proto.Client, com.publica.storm.s3.proto.Client.Builder, com.publica.storm.s3.proto.ClientOrBuilder> clientBuilder_;
    /**
     * <code>optional .logger.Client client = 3;</code>
     */
    public boolean hasClient() {
      return clientBuilder_ != null || client_ != null;
    }
    /**
     * <code>optional .logger.Client client = 3;</code>
     */
    public com.publica.storm.s3.proto.Client getClient() {
      if (clientBuilder_ == null) {
        return client_ == null ? com.publica.storm.s3.proto.Client.getDefaultInstance() : client_;
      } else {
        return clientBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .logger.Client client = 3;</code>
     */
    public Builder setClient(com.publica.storm.s3.proto.Client value) {
      if (clientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        client_ = value;
        onChanged();
      } else {
        clientBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .logger.Client client = 3;</code>
     */
    public Builder setClient(
        com.publica.storm.s3.proto.Client.Builder builderForValue) {
      if (clientBuilder_ == null) {
        client_ = builderForValue.build();
        onChanged();
      } else {
        clientBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .logger.Client client = 3;</code>
     */
    public Builder mergeClient(com.publica.storm.s3.proto.Client value) {
      if (clientBuilder_ == null) {
        if (client_ != null) {
          client_ =
            com.publica.storm.s3.proto.Client.newBuilder(client_).mergeFrom(value).buildPartial();
        } else {
          client_ = value;
        }
        onChanged();
      } else {
        clientBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .logger.Client client = 3;</code>
     */
    public Builder clearClient() {
      if (clientBuilder_ == null) {
        client_ = null;
        onChanged();
      } else {
        client_ = null;
        clientBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .logger.Client client = 3;</code>
     */
    public com.publica.storm.s3.proto.Client.Builder getClientBuilder() {
      
      onChanged();
      return getClientFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .logger.Client client = 3;</code>
     */
    public com.publica.storm.s3.proto.ClientOrBuilder getClientOrBuilder() {
      if (clientBuilder_ != null) {
        return clientBuilder_.getMessageOrBuilder();
      } else {
        return client_ == null ?
            com.publica.storm.s3.proto.Client.getDefaultInstance() : client_;
      }
    }
    /**
     * <code>optional .logger.Client client = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.publica.storm.s3.proto.Client, com.publica.storm.s3.proto.Client.Builder, com.publica.storm.s3.proto.ClientOrBuilder> 
        getClientFieldBuilder() {
      if (clientBuilder_ == null) {
        clientBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.publica.storm.s3.proto.Client, com.publica.storm.s3.proto.Client.Builder, com.publica.storm.s3.proto.ClientOrBuilder>(
                getClient(),
                getParentForChildren(),
                isClean());
        client_ = null;
      }
      return clientBuilder_;
    }

    private com.publica.storm.s3.proto.User user_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.publica.storm.s3.proto.User, com.publica.storm.s3.proto.User.Builder, com.publica.storm.s3.proto.UserOrBuilder> userBuilder_;
    /**
     * <code>optional .logger.User user = 4;</code>
     */
    public boolean hasUser() {
      return userBuilder_ != null || user_ != null;
    }
    /**
     * <code>optional .logger.User user = 4;</code>
     */
    public com.publica.storm.s3.proto.User getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? com.publica.storm.s3.proto.User.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .logger.User user = 4;</code>
     */
    public Builder setUser(com.publica.storm.s3.proto.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .logger.User user = 4;</code>
     */
    public Builder setUser(
        com.publica.storm.s3.proto.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .logger.User user = 4;</code>
     */
    public Builder mergeUser(com.publica.storm.s3.proto.User value) {
      if (userBuilder_ == null) {
        if (user_ != null) {
          user_ =
            com.publica.storm.s3.proto.User.newBuilder(user_).mergeFrom(value).buildPartial();
        } else {
          user_ = value;
        }
        onChanged();
      } else {
        userBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .logger.User user = 4;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = null;
        onChanged();
      } else {
        user_ = null;
        userBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .logger.User user = 4;</code>
     */
    public com.publica.storm.s3.proto.User.Builder getUserBuilder() {
      
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .logger.User user = 4;</code>
     */
    public com.publica.storm.s3.proto.UserOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            com.publica.storm.s3.proto.User.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>optional .logger.User user = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.publica.storm.s3.proto.User, com.publica.storm.s3.proto.User.Builder, com.publica.storm.s3.proto.UserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.publica.storm.s3.proto.User, com.publica.storm.s3.proto.User.Builder, com.publica.storm.s3.proto.UserOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private java.util.List<com.publica.storm.s3.proto.Pair> custom_ =
      java.util.Collections.emptyList();
    private void ensureCustomIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        custom_ = new java.util.ArrayList<com.publica.storm.s3.proto.Pair>(custom_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.publica.storm.s3.proto.Pair, com.publica.storm.s3.proto.Pair.Builder, com.publica.storm.s3.proto.PairOrBuilder> customBuilder_;

    /**
     * <code>repeated .logger.Pair custom = 5;</code>
     */
    public java.util.List<com.publica.storm.s3.proto.Pair> getCustomList() {
      if (customBuilder_ == null) {
        return java.util.Collections.unmodifiableList(custom_);
      } else {
        return customBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .logger.Pair custom = 5;</code>
     */
    public int getCustomCount() {
      if (customBuilder_ == null) {
        return custom_.size();
      } else {
        return customBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .logger.Pair custom = 5;</code>
     */
    public com.publica.storm.s3.proto.Pair getCustom(int index) {
      if (customBuilder_ == null) {
        return custom_.get(index);
      } else {
        return customBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .logger.Pair custom = 5;</code>
     */
    public Builder setCustom(
        int index, com.publica.storm.s3.proto.Pair value) {
      if (customBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCustomIsMutable();
        custom_.set(index, value);
        onChanged();
      } else {
        customBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .logger.Pair custom = 5;</code>
     */
    public Builder setCustom(
        int index, com.publica.storm.s3.proto.Pair.Builder builderForValue) {
      if (customBuilder_ == null) {
        ensureCustomIsMutable();
        custom_.set(index, builderForValue.build());
        onChanged();
      } else {
        customBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .logger.Pair custom = 5;</code>
     */
    public Builder addCustom(com.publica.storm.s3.proto.Pair value) {
      if (customBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCustomIsMutable();
        custom_.add(value);
        onChanged();
      } else {
        customBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .logger.Pair custom = 5;</code>
     */
    public Builder addCustom(
        int index, com.publica.storm.s3.proto.Pair value) {
      if (customBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCustomIsMutable();
        custom_.add(index, value);
        onChanged();
      } else {
        customBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .logger.Pair custom = 5;</code>
     */
    public Builder addCustom(
        com.publica.storm.s3.proto.Pair.Builder builderForValue) {
      if (customBuilder_ == null) {
        ensureCustomIsMutable();
        custom_.add(builderForValue.build());
        onChanged();
      } else {
        customBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .logger.Pair custom = 5;</code>
     */
    public Builder addCustom(
        int index, com.publica.storm.s3.proto.Pair.Builder builderForValue) {
      if (customBuilder_ == null) {
        ensureCustomIsMutable();
        custom_.add(index, builderForValue.build());
        onChanged();
      } else {
        customBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .logger.Pair custom = 5;</code>
     */
    public Builder addAllCustom(
        java.lang.Iterable<? extends com.publica.storm.s3.proto.Pair> values) {
      if (customBuilder_ == null) {
        ensureCustomIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, custom_);
        onChanged();
      } else {
        customBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .logger.Pair custom = 5;</code>
     */
    public Builder clearCustom() {
      if (customBuilder_ == null) {
        custom_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        customBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .logger.Pair custom = 5;</code>
     */
    public Builder removeCustom(int index) {
      if (customBuilder_ == null) {
        ensureCustomIsMutable();
        custom_.remove(index);
        onChanged();
      } else {
        customBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .logger.Pair custom = 5;</code>
     */
    public com.publica.storm.s3.proto.Pair.Builder getCustomBuilder(
        int index) {
      return getCustomFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .logger.Pair custom = 5;</code>
     */
    public com.publica.storm.s3.proto.PairOrBuilder getCustomOrBuilder(
        int index) {
      if (customBuilder_ == null) {
        return custom_.get(index);  } else {
        return customBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .logger.Pair custom = 5;</code>
     */
    public java.util.List<? extends com.publica.storm.s3.proto.PairOrBuilder> 
         getCustomOrBuilderList() {
      if (customBuilder_ != null) {
        return customBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(custom_);
      }
    }
    /**
     * <code>repeated .logger.Pair custom = 5;</code>
     */
    public com.publica.storm.s3.proto.Pair.Builder addCustomBuilder() {
      return getCustomFieldBuilder().addBuilder(
          com.publica.storm.s3.proto.Pair.getDefaultInstance());
    }
    /**
     * <code>repeated .logger.Pair custom = 5;</code>
     */
    public com.publica.storm.s3.proto.Pair.Builder addCustomBuilder(
        int index) {
      return getCustomFieldBuilder().addBuilder(
          index, com.publica.storm.s3.proto.Pair.getDefaultInstance());
    }
    /**
     * <code>repeated .logger.Pair custom = 5;</code>
     */
    public java.util.List<com.publica.storm.s3.proto.Pair.Builder> 
         getCustomBuilderList() {
      return getCustomFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.publica.storm.s3.proto.Pair, com.publica.storm.s3.proto.Pair.Builder, com.publica.storm.s3.proto.PairOrBuilder> 
        getCustomFieldBuilder() {
      if (customBuilder_ == null) {
        customBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.publica.storm.s3.proto.Pair, com.publica.storm.s3.proto.Pair.Builder, com.publica.storm.s3.proto.PairOrBuilder>(
                custom_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        custom_ = null;
      }
      return customBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:logger.Error)
  }

  // @@protoc_insertion_point(class_scope:logger.Error)
  private static final com.publica.storm.s3.proto.Error DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.publica.storm.s3.proto.Error();
  }

  public static com.publica.storm.s3.proto.Error getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Error>
      PARSER = new com.google.protobuf.AbstractParser<Error>() {
    public Error parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Error(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Error> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Error> getParserForType() {
    return PARSER;
  }

  public com.publica.storm.s3.proto.Error getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

