// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.publica.storm.s3.proto;

public final class LoggerProto {
  private LoggerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_logger_Client_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_logger_Client_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_logger_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_logger_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_logger_User_GeoIP_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_logger_User_GeoIP_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_logger_Pair_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_logger_Pair_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_logger_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_logger_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_logger_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_logger_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_logger_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_logger_Error_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\006logger\032\037google/protobuf" +
      "/timestamp.proto\"\"\n\006Client\022\013\n\003pID\030\001 \001(\t\022" +
      "\013\n\003sID\030\002 \001(\t\"\370\001\n\004User\022\016\n\006sessID\030\001 \001(\t\022\014\n" +
      "\004path\030\002 \001(\t\022\021\n\tadblocker\030\003 \001(\010\022\013\n\003uID\030\004 " +
      "\001(\t\022\014\n\004puID\030\005 \001(\t\022\022\n\nuser_agent\030\006 \001(\t\022\016\n" +
      "\006device\030\007 \001(\t\022\016\n\006domain\030\010 \001(\t\022\026\n\016page_lo" +
      "ad_time\030\t \001(\004\022$\n\010location\030\n \001(\0132\022.logger" +
      ".User.GeoIP\0322\n\005GeoIP\022\n\n\002IP\030\001 \001(\t\022\017\n\007coun" +
      "try\030\002 \001(\t\022\014\n\004city\030\003 \001(\t\"\"\n\004Pair\022\013\n\003key\030\001" +
      " \001(\t\022\r\n\005value\030\002 \001(\t\"\275\002\n\005Event\022 \n\004type\030\001 ",
      "\001(\0162\022.logger.Event.Type\022-\n\ttimestamp\030\002 \001" +
      "(\0132\032.google.protobuf.Timestamp\022\036\n\006client" +
      "\030\003 \001(\0132\016.logger.Client\022\032\n\004user\030\004 \001(\0132\014.l" +
      "ogger.User\022\034\n\006custom\030\005 \003(\0132\014.logger.Pair" +
      "\"\210\001\n\004Type\022\025\n\021BOOTLOADER_LOADED\020\000\022\024\n\020DISC" +
      "OVERY_LOADED\020\001\022\020\n\014SESSION_PING\020\002\022\r\n\tPAGE" +
      "_VIEW\020\003\022\016\n\nIMPRESSION\020\004\022\t\n\005CLICK\020\005\022\010\n\004SK" +
      "IP\020\006\022\r\n\tON_SCREEN\020\007\"\007\n\005Empty\"\244\001\n\005Error\022\022" +
      "\n\nerror_code\030\001 \001(\r\022-\n\ttimestamp\030\002 \001(\0132\032." +
      "google.protobuf.Timestamp\022\036\n\006client\030\003 \001(",
      "\0132\016.logger.Client\022\032\n\004user\030\004 \001(\0132\014.logger" +
      ".User\022\034\n\006custom\030\005 \003(\0132\014.logger.Pair2`\n\006L" +
      "ogger\022*\n\010LogEvent\022\r.logger.Event\032\r.logge" +
      "r.Empty\"\000\022*\n\010LogError\022\r.logger.Error\032\r.l" +
      "ogger.Empty\"\000B.\n\032com.publica.storm.s3.pr" +
      "otoB\013LoggerProtoP\001\240\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_logger_Client_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_logger_Client_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_logger_Client_descriptor,
        new java.lang.String[] { "PID", "SID", });
    internal_static_logger_User_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_logger_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_logger_User_descriptor,
        new java.lang.String[] { "SessID", "Path", "Adblocker", "UID", "PuID", "UserAgent", "Device", "Domain", "PageLoadTime", "Location", });
    internal_static_logger_User_GeoIP_descriptor =
      internal_static_logger_User_descriptor.getNestedTypes().get(0);
    internal_static_logger_User_GeoIP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_logger_User_GeoIP_descriptor,
        new java.lang.String[] { "IP", "Country", "City", });
    internal_static_logger_Pair_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_logger_Pair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_logger_Pair_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_logger_Event_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_logger_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_logger_Event_descriptor,
        new java.lang.String[] { "Type", "Timestamp", "Client", "User", "Custom", });
    internal_static_logger_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_logger_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_logger_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_logger_Error_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_logger_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_logger_Error_descriptor,
        new java.lang.String[] { "ErrorCode", "Timestamp", "Client", "User", "Custom", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
