// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.publica.storm.s3.proto;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:logger.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string sessID = 1;</code>
   */
  java.lang.String getSessID();
  /**
   * <code>optional string sessID = 1;</code>
   */
  com.google.protobuf.ByteString
      getSessIDBytes();

  /**
   * <code>optional string path = 2;</code>
   */
  java.lang.String getPath();
  /**
   * <code>optional string path = 2;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>optional bool adblocker = 3;</code>
   */
  boolean getAdblocker();

  /**
   * <code>optional string uID = 4;</code>
   */
  java.lang.String getUID();
  /**
   * <code>optional string uID = 4;</code>
   */
  com.google.protobuf.ByteString
      getUIDBytes();

  /**
   * <code>optional string puID = 5;</code>
   */
  java.lang.String getPuID();
  /**
   * <code>optional string puID = 5;</code>
   */
  com.google.protobuf.ByteString
      getPuIDBytes();

  /**
   * <code>optional string user_agent = 6;</code>
   */
  java.lang.String getUserAgent();
  /**
   * <code>optional string user_agent = 6;</code>
   */
  com.google.protobuf.ByteString
      getUserAgentBytes();

  /**
   * <code>optional string device = 7;</code>
   */
  java.lang.String getDevice();
  /**
   * <code>optional string device = 7;</code>
   */
  com.google.protobuf.ByteString
      getDeviceBytes();

  /**
   * <code>optional string domain = 8;</code>
   */
  java.lang.String getDomain();
  /**
   * <code>optional string domain = 8;</code>
   */
  com.google.protobuf.ByteString
      getDomainBytes();

  /**
   * <code>optional uint64 page_load_time = 9;</code>
   */
  long getPageLoadTime();

  /**
   * <code>optional .logger.User.GeoIP location = 10;</code>
   */
  boolean hasLocation();
  /**
   * <code>optional .logger.User.GeoIP location = 10;</code>
   */
  com.publica.storm.s3.proto.User.GeoIP getLocation();
  /**
   * <code>optional .logger.User.GeoIP location = 10;</code>
   */
  com.publica.storm.s3.proto.User.GeoIPOrBuilder getLocationOrBuilder();
}
