// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.publica.storm.s3.proto;

/**
 * Protobuf type {@code logger.User}
 */
public  final class User extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:logger.User)
    UserOrBuilder {
  // Use User.newBuilder() to construct.
  private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private User() {
    sessID_ = "";
    path_ = "";
    adblocker_ = false;
    uID_ = "";
    puID_ = "";
    userAgent_ = "";
    device_ = "";
    domain_ = "";
    pageLoadTime_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private User(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            sessID_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            path_ = s;
            break;
          }
          case 24: {

            adblocker_ = input.readBool();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            uID_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            puID_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            userAgent_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            device_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            domain_ = s;
            break;
          }
          case 72: {

            pageLoadTime_ = input.readUInt64();
            break;
          }
          case 82: {
            com.publica.storm.s3.proto.User.GeoIP.Builder subBuilder = null;
            if (location_ != null) {
              subBuilder = location_.toBuilder();
            }
            location_ = input.readMessage(com.publica.storm.s3.proto.User.GeoIP.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(location_);
              location_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_User_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_User_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.publica.storm.s3.proto.User.class, com.publica.storm.s3.proto.User.Builder.class);
  }

  public interface GeoIPOrBuilder extends
      // @@protoc_insertion_point(interface_extends:logger.User.GeoIP)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string IP = 1;</code>
     */
    java.lang.String getIP();
    /**
     * <code>optional string IP = 1;</code>
     */
    com.google.protobuf.ByteString
        getIPBytes();

    /**
     * <code>optional string country = 2;</code>
     */
    java.lang.String getCountry();
    /**
     * <code>optional string country = 2;</code>
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <code>optional string city = 3;</code>
     */
    java.lang.String getCity();
    /**
     * <code>optional string city = 3;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();
  }
  /**
   * Protobuf type {@code logger.User.GeoIP}
   */
  public  static final class GeoIP extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:logger.User.GeoIP)
      GeoIPOrBuilder {
    // Use GeoIP.newBuilder() to construct.
    private GeoIP(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GeoIP() {
      iP_ = "";
      country_ = "";
      city_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GeoIP(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              iP_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              country_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              city_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_User_GeoIP_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_User_GeoIP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.publica.storm.s3.proto.User.GeoIP.class, com.publica.storm.s3.proto.User.GeoIP.Builder.class);
    }

    public static final int IP_FIELD_NUMBER = 1;
    private volatile java.lang.Object iP_;
    /**
     * <code>optional string IP = 1;</code>
     */
    public java.lang.String getIP() {
      java.lang.Object ref = iP_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iP_ = s;
        return s;
      }
    }
    /**
     * <code>optional string IP = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIPBytes() {
      java.lang.Object ref = iP_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRY_FIELD_NUMBER = 2;
    private volatile java.lang.Object country_;
    /**
     * <code>optional string country = 2;</code>
     */
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        country_ = s;
        return s;
      }
    }
    /**
     * <code>optional string country = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 3;
    private volatile java.lang.Object city_;
    /**
     * <code>optional string city = 3;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>optional string city = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIPBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, iP_);
      }
      if (!getCountryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, country_);
      }
      if (!getCityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, city_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIPBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, iP_);
      }
      if (!getCountryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, country_);
      }
      if (!getCityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, city_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.publica.storm.s3.proto.User.GeoIP)) {
        return super.equals(obj);
      }
      com.publica.storm.s3.proto.User.GeoIP other = (com.publica.storm.s3.proto.User.GeoIP) obj;

      boolean result = true;
      result = result && getIP()
          .equals(other.getIP());
      result = result && getCountry()
          .equals(other.getCountry());
      result = result && getCity()
          .equals(other.getCity());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIP().hashCode();
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getCountry().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.publica.storm.s3.proto.User.GeoIP parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.publica.storm.s3.proto.User.GeoIP parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.publica.storm.s3.proto.User.GeoIP parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.publica.storm.s3.proto.User.GeoIP parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.publica.storm.s3.proto.User.GeoIP parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.publica.storm.s3.proto.User.GeoIP parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.publica.storm.s3.proto.User.GeoIP parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.publica.storm.s3.proto.User.GeoIP parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.publica.storm.s3.proto.User.GeoIP parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.publica.storm.s3.proto.User.GeoIP parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.publica.storm.s3.proto.User.GeoIP prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code logger.User.GeoIP}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:logger.User.GeoIP)
        com.publica.storm.s3.proto.User.GeoIPOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_User_GeoIP_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_User_GeoIP_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.publica.storm.s3.proto.User.GeoIP.class, com.publica.storm.s3.proto.User.GeoIP.Builder.class);
      }

      // Construct using com.publica.storm.s3.proto.User.GeoIP.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        iP_ = "";

        country_ = "";

        city_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_User_GeoIP_descriptor;
      }

      public com.publica.storm.s3.proto.User.GeoIP getDefaultInstanceForType() {
        return com.publica.storm.s3.proto.User.GeoIP.getDefaultInstance();
      }

      public com.publica.storm.s3.proto.User.GeoIP build() {
        com.publica.storm.s3.proto.User.GeoIP result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.publica.storm.s3.proto.User.GeoIP buildPartial() {
        com.publica.storm.s3.proto.User.GeoIP result = new com.publica.storm.s3.proto.User.GeoIP(this);
        result.iP_ = iP_;
        result.country_ = country_;
        result.city_ = city_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.publica.storm.s3.proto.User.GeoIP) {
          return mergeFrom((com.publica.storm.s3.proto.User.GeoIP)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.publica.storm.s3.proto.User.GeoIP other) {
        if (other == com.publica.storm.s3.proto.User.GeoIP.getDefaultInstance()) return this;
        if (!other.getIP().isEmpty()) {
          iP_ = other.iP_;
          onChanged();
        }
        if (!other.getCountry().isEmpty()) {
          country_ = other.country_;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.publica.storm.s3.proto.User.GeoIP parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.publica.storm.s3.proto.User.GeoIP) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object iP_ = "";
      /**
       * <code>optional string IP = 1;</code>
       */
      public java.lang.String getIP() {
        java.lang.Object ref = iP_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iP_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string IP = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIPBytes() {
        java.lang.Object ref = iP_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string IP = 1;</code>
       */
      public Builder setIP(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string IP = 1;</code>
       */
      public Builder clearIP() {
        
        iP_ = getDefaultInstance().getIP();
        onChanged();
        return this;
      }
      /**
       * <code>optional string IP = 1;</code>
       */
      public Builder setIPBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        iP_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object country_ = "";
      /**
       * <code>optional string country = 2;</code>
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string country = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string country = 2;</code>
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string country = 2;</code>
       */
      public Builder clearCountry() {
        
        country_ = getDefaultInstance().getCountry();
        onChanged();
        return this;
      }
      /**
       * <code>optional string country = 2;</code>
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        country_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>optional string city = 3;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string city = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string city = 3;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 3;</code>
       */
      public Builder clearCity() {
        
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 3;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        city_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:logger.User.GeoIP)
    }

    // @@protoc_insertion_point(class_scope:logger.User.GeoIP)
    private static final com.publica.storm.s3.proto.User.GeoIP DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.publica.storm.s3.proto.User.GeoIP();
    }

    public static com.publica.storm.s3.proto.User.GeoIP getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GeoIP>
        PARSER = new com.google.protobuf.AbstractParser<GeoIP>() {
      public GeoIP parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GeoIP(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GeoIP> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GeoIP> getParserForType() {
      return PARSER;
    }

    public com.publica.storm.s3.proto.User.GeoIP getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int SESSID_FIELD_NUMBER = 1;
  private volatile java.lang.Object sessID_;
  /**
   * <code>optional string sessID = 1;</code>
   */
  public java.lang.String getSessID() {
    java.lang.Object ref = sessID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessID_ = s;
      return s;
    }
  }
  /**
   * <code>optional string sessID = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSessIDBytes() {
    java.lang.Object ref = sessID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATH_FIELD_NUMBER = 2;
  private volatile java.lang.Object path_;
  /**
   * <code>optional string path = 2;</code>
   */
  public java.lang.String getPath() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      path_ = s;
      return s;
    }
  }
  /**
   * <code>optional string path = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPathBytes() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      path_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADBLOCKER_FIELD_NUMBER = 3;
  private boolean adblocker_;
  /**
   * <code>optional bool adblocker = 3;</code>
   */
  public boolean getAdblocker() {
    return adblocker_;
  }

  public static final int UID_FIELD_NUMBER = 4;
  private volatile java.lang.Object uID_;
  /**
   * <code>optional string uID = 4;</code>
   */
  public java.lang.String getUID() {
    java.lang.Object ref = uID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uID_ = s;
      return s;
    }
  }
  /**
   * <code>optional string uID = 4;</code>
   */
  public com.google.protobuf.ByteString
      getUIDBytes() {
    java.lang.Object ref = uID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PUID_FIELD_NUMBER = 5;
  private volatile java.lang.Object puID_;
  /**
   * <code>optional string puID = 5;</code>
   */
  public java.lang.String getPuID() {
    java.lang.Object ref = puID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      puID_ = s;
      return s;
    }
  }
  /**
   * <code>optional string puID = 5;</code>
   */
  public com.google.protobuf.ByteString
      getPuIDBytes() {
    java.lang.Object ref = puID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      puID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_AGENT_FIELD_NUMBER = 6;
  private volatile java.lang.Object userAgent_;
  /**
   * <code>optional string user_agent = 6;</code>
   */
  public java.lang.String getUserAgent() {
    java.lang.Object ref = userAgent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userAgent_ = s;
      return s;
    }
  }
  /**
   * <code>optional string user_agent = 6;</code>
   */
  public com.google.protobuf.ByteString
      getUserAgentBytes() {
    java.lang.Object ref = userAgent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userAgent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_FIELD_NUMBER = 7;
  private volatile java.lang.Object device_;
  /**
   * <code>optional string device = 7;</code>
   */
  public java.lang.String getDevice() {
    java.lang.Object ref = device_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      device_ = s;
      return s;
    }
  }
  /**
   * <code>optional string device = 7;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceBytes() {
    java.lang.Object ref = device_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      device_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOMAIN_FIELD_NUMBER = 8;
  private volatile java.lang.Object domain_;
  /**
   * <code>optional string domain = 8;</code>
   */
  public java.lang.String getDomain() {
    java.lang.Object ref = domain_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      domain_ = s;
      return s;
    }
  }
  /**
   * <code>optional string domain = 8;</code>
   */
  public com.google.protobuf.ByteString
      getDomainBytes() {
    java.lang.Object ref = domain_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      domain_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGE_LOAD_TIME_FIELD_NUMBER = 9;
  private long pageLoadTime_;
  /**
   * <code>optional uint64 page_load_time = 9;</code>
   */
  public long getPageLoadTime() {
    return pageLoadTime_;
  }

  public static final int LOCATION_FIELD_NUMBER = 10;
  private com.publica.storm.s3.proto.User.GeoIP location_;
  /**
   * <code>optional .logger.User.GeoIP location = 10;</code>
   */
  public boolean hasLocation() {
    return location_ != null;
  }
  /**
   * <code>optional .logger.User.GeoIP location = 10;</code>
   */
  public com.publica.storm.s3.proto.User.GeoIP getLocation() {
    return location_ == null ? com.publica.storm.s3.proto.User.GeoIP.getDefaultInstance() : location_;
  }
  /**
   * <code>optional .logger.User.GeoIP location = 10;</code>
   */
  public com.publica.storm.s3.proto.User.GeoIPOrBuilder getLocationOrBuilder() {
    return getLocation();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSessIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sessID_);
    }
    if (!getPathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, path_);
    }
    if (adblocker_ != false) {
      output.writeBool(3, adblocker_);
    }
    if (!getUIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, uID_);
    }
    if (!getPuIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, puID_);
    }
    if (!getUserAgentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, userAgent_);
    }
    if (!getDeviceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, device_);
    }
    if (!getDomainBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, domain_);
    }
    if (pageLoadTime_ != 0L) {
      output.writeUInt64(9, pageLoadTime_);
    }
    if (location_ != null) {
      output.writeMessage(10, getLocation());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSessIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessID_);
    }
    if (!getPathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, path_);
    }
    if (adblocker_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, adblocker_);
    }
    if (!getUIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, uID_);
    }
    if (!getPuIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, puID_);
    }
    if (!getUserAgentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, userAgent_);
    }
    if (!getDeviceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, device_);
    }
    if (!getDomainBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, domain_);
    }
    if (pageLoadTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, pageLoadTime_);
    }
    if (location_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getLocation());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.publica.storm.s3.proto.User)) {
      return super.equals(obj);
    }
    com.publica.storm.s3.proto.User other = (com.publica.storm.s3.proto.User) obj;

    boolean result = true;
    result = result && getSessID()
        .equals(other.getSessID());
    result = result && getPath()
        .equals(other.getPath());
    result = result && (getAdblocker()
        == other.getAdblocker());
    result = result && getUID()
        .equals(other.getUID());
    result = result && getPuID()
        .equals(other.getPuID());
    result = result && getUserAgent()
        .equals(other.getUserAgent());
    result = result && getDevice()
        .equals(other.getDevice());
    result = result && getDomain()
        .equals(other.getDomain());
    result = result && (getPageLoadTime()
        == other.getPageLoadTime());
    result = result && (hasLocation() == other.hasLocation());
    if (hasLocation()) {
      result = result && getLocation()
          .equals(other.getLocation());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + SESSID_FIELD_NUMBER;
    hash = (53 * hash) + getSessID().hashCode();
    hash = (37 * hash) + PATH_FIELD_NUMBER;
    hash = (53 * hash) + getPath().hashCode();
    hash = (37 * hash) + ADBLOCKER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAdblocker());
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + getUID().hashCode();
    hash = (37 * hash) + PUID_FIELD_NUMBER;
    hash = (53 * hash) + getPuID().hashCode();
    hash = (37 * hash) + USER_AGENT_FIELD_NUMBER;
    hash = (53 * hash) + getUserAgent().hashCode();
    hash = (37 * hash) + DEVICE_FIELD_NUMBER;
    hash = (53 * hash) + getDevice().hashCode();
    hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
    hash = (53 * hash) + getDomain().hashCode();
    hash = (37 * hash) + PAGE_LOAD_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPageLoadTime());
    if (hasLocation()) {
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.publica.storm.s3.proto.User parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.publica.storm.s3.proto.User parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.publica.storm.s3.proto.User parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.publica.storm.s3.proto.User parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.publica.storm.s3.proto.User parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.publica.storm.s3.proto.User parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.publica.storm.s3.proto.User parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.publica.storm.s3.proto.User parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.publica.storm.s3.proto.User parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.publica.storm.s3.proto.User parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.publica.storm.s3.proto.User prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code logger.User}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:logger.User)
      com.publica.storm.s3.proto.UserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.publica.storm.s3.proto.User.class, com.publica.storm.s3.proto.User.Builder.class);
    }

    // Construct using com.publica.storm.s3.proto.User.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      sessID_ = "";

      path_ = "";

      adblocker_ = false;

      uID_ = "";

      puID_ = "";

      userAgent_ = "";

      device_ = "";

      domain_ = "";

      pageLoadTime_ = 0L;

      if (locationBuilder_ == null) {
        location_ = null;
      } else {
        location_ = null;
        locationBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.publica.storm.s3.proto.LoggerProto.internal_static_logger_User_descriptor;
    }

    public com.publica.storm.s3.proto.User getDefaultInstanceForType() {
      return com.publica.storm.s3.proto.User.getDefaultInstance();
    }

    public com.publica.storm.s3.proto.User build() {
      com.publica.storm.s3.proto.User result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.publica.storm.s3.proto.User buildPartial() {
      com.publica.storm.s3.proto.User result = new com.publica.storm.s3.proto.User(this);
      result.sessID_ = sessID_;
      result.path_ = path_;
      result.adblocker_ = adblocker_;
      result.uID_ = uID_;
      result.puID_ = puID_;
      result.userAgent_ = userAgent_;
      result.device_ = device_;
      result.domain_ = domain_;
      result.pageLoadTime_ = pageLoadTime_;
      if (locationBuilder_ == null) {
        result.location_ = location_;
      } else {
        result.location_ = locationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.publica.storm.s3.proto.User) {
        return mergeFrom((com.publica.storm.s3.proto.User)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.publica.storm.s3.proto.User other) {
      if (other == com.publica.storm.s3.proto.User.getDefaultInstance()) return this;
      if (!other.getSessID().isEmpty()) {
        sessID_ = other.sessID_;
        onChanged();
      }
      if (!other.getPath().isEmpty()) {
        path_ = other.path_;
        onChanged();
      }
      if (other.getAdblocker() != false) {
        setAdblocker(other.getAdblocker());
      }
      if (!other.getUID().isEmpty()) {
        uID_ = other.uID_;
        onChanged();
      }
      if (!other.getPuID().isEmpty()) {
        puID_ = other.puID_;
        onChanged();
      }
      if (!other.getUserAgent().isEmpty()) {
        userAgent_ = other.userAgent_;
        onChanged();
      }
      if (!other.getDevice().isEmpty()) {
        device_ = other.device_;
        onChanged();
      }
      if (!other.getDomain().isEmpty()) {
        domain_ = other.domain_;
        onChanged();
      }
      if (other.getPageLoadTime() != 0L) {
        setPageLoadTime(other.getPageLoadTime());
      }
      if (other.hasLocation()) {
        mergeLocation(other.getLocation());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.publica.storm.s3.proto.User parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.publica.storm.s3.proto.User) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object sessID_ = "";
    /**
     * <code>optional string sessID = 1;</code>
     */
    public java.lang.String getSessID() {
      java.lang.Object ref = sessID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sessID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSessIDBytes() {
      java.lang.Object ref = sessID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sessID = 1;</code>
     */
    public Builder setSessID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sessID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sessID = 1;</code>
     */
    public Builder clearSessID() {
      
      sessID_ = getDefaultInstance().getSessID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sessID = 1;</code>
     */
    public Builder setSessIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sessID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object path_ = "";
    /**
     * <code>optional string path = 2;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string path = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string path = 2;</code>
     */
    public Builder setPath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      path_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string path = 2;</code>
     */
    public Builder clearPath() {
      
      path_ = getDefaultInstance().getPath();
      onChanged();
      return this;
    }
    /**
     * <code>optional string path = 2;</code>
     */
    public Builder setPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      path_ = value;
      onChanged();
      return this;
    }

    private boolean adblocker_ ;
    /**
     * <code>optional bool adblocker = 3;</code>
     */
    public boolean getAdblocker() {
      return adblocker_;
    }
    /**
     * <code>optional bool adblocker = 3;</code>
     */
    public Builder setAdblocker(boolean value) {
      
      adblocker_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool adblocker = 3;</code>
     */
    public Builder clearAdblocker() {
      
      adblocker_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object uID_ = "";
    /**
     * <code>optional string uID = 4;</code>
     */
    public java.lang.String getUID() {
      java.lang.Object ref = uID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string uID = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUIDBytes() {
      java.lang.Object ref = uID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string uID = 4;</code>
     */
    public Builder setUID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string uID = 4;</code>
     */
    public Builder clearUID() {
      
      uID_ = getDefaultInstance().getUID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string uID = 4;</code>
     */
    public Builder setUIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object puID_ = "";
    /**
     * <code>optional string puID = 5;</code>
     */
    public java.lang.String getPuID() {
      java.lang.Object ref = puID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        puID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string puID = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPuIDBytes() {
      java.lang.Object ref = puID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        puID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string puID = 5;</code>
     */
    public Builder setPuID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      puID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string puID = 5;</code>
     */
    public Builder clearPuID() {
      
      puID_ = getDefaultInstance().getPuID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string puID = 5;</code>
     */
    public Builder setPuIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      puID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userAgent_ = "";
    /**
     * <code>optional string user_agent = 6;</code>
     */
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userAgent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string user_agent = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string user_agent = 6;</code>
     */
    public Builder setUserAgent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userAgent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string user_agent = 6;</code>
     */
    public Builder clearUserAgent() {
      
      userAgent_ = getDefaultInstance().getUserAgent();
      onChanged();
      return this;
    }
    /**
     * <code>optional string user_agent = 6;</code>
     */
    public Builder setUserAgentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userAgent_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object device_ = "";
    /**
     * <code>optional string device = 7;</code>
     */
    public java.lang.String getDevice() {
      java.lang.Object ref = device_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        device_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string device = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceBytes() {
      java.lang.Object ref = device_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        device_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string device = 7;</code>
     */
    public Builder setDevice(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      device_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string device = 7;</code>
     */
    public Builder clearDevice() {
      
      device_ = getDefaultInstance().getDevice();
      onChanged();
      return this;
    }
    /**
     * <code>optional string device = 7;</code>
     */
    public Builder setDeviceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      device_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object domain_ = "";
    /**
     * <code>optional string domain = 8;</code>
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domain_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string domain = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string domain = 8;</code>
     */
    public Builder setDomain(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      domain_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string domain = 8;</code>
     */
    public Builder clearDomain() {
      
      domain_ = getDefaultInstance().getDomain();
      onChanged();
      return this;
    }
    /**
     * <code>optional string domain = 8;</code>
     */
    public Builder setDomainBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      domain_ = value;
      onChanged();
      return this;
    }

    private long pageLoadTime_ ;
    /**
     * <code>optional uint64 page_load_time = 9;</code>
     */
    public long getPageLoadTime() {
      return pageLoadTime_;
    }
    /**
     * <code>optional uint64 page_load_time = 9;</code>
     */
    public Builder setPageLoadTime(long value) {
      
      pageLoadTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 page_load_time = 9;</code>
     */
    public Builder clearPageLoadTime() {
      
      pageLoadTime_ = 0L;
      onChanged();
      return this;
    }

    private com.publica.storm.s3.proto.User.GeoIP location_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.publica.storm.s3.proto.User.GeoIP, com.publica.storm.s3.proto.User.GeoIP.Builder, com.publica.storm.s3.proto.User.GeoIPOrBuilder> locationBuilder_;
    /**
     * <code>optional .logger.User.GeoIP location = 10;</code>
     */
    public boolean hasLocation() {
      return locationBuilder_ != null || location_ != null;
    }
    /**
     * <code>optional .logger.User.GeoIP location = 10;</code>
     */
    public com.publica.storm.s3.proto.User.GeoIP getLocation() {
      if (locationBuilder_ == null) {
        return location_ == null ? com.publica.storm.s3.proto.User.GeoIP.getDefaultInstance() : location_;
      } else {
        return locationBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .logger.User.GeoIP location = 10;</code>
     */
    public Builder setLocation(com.publica.storm.s3.proto.User.GeoIP value) {
      if (locationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        location_ = value;
        onChanged();
      } else {
        locationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .logger.User.GeoIP location = 10;</code>
     */
    public Builder setLocation(
        com.publica.storm.s3.proto.User.GeoIP.Builder builderForValue) {
      if (locationBuilder_ == null) {
        location_ = builderForValue.build();
        onChanged();
      } else {
        locationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .logger.User.GeoIP location = 10;</code>
     */
    public Builder mergeLocation(com.publica.storm.s3.proto.User.GeoIP value) {
      if (locationBuilder_ == null) {
        if (location_ != null) {
          location_ =
            com.publica.storm.s3.proto.User.GeoIP.newBuilder(location_).mergeFrom(value).buildPartial();
        } else {
          location_ = value;
        }
        onChanged();
      } else {
        locationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .logger.User.GeoIP location = 10;</code>
     */
    public Builder clearLocation() {
      if (locationBuilder_ == null) {
        location_ = null;
        onChanged();
      } else {
        location_ = null;
        locationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .logger.User.GeoIP location = 10;</code>
     */
    public com.publica.storm.s3.proto.User.GeoIP.Builder getLocationBuilder() {
      
      onChanged();
      return getLocationFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .logger.User.GeoIP location = 10;</code>
     */
    public com.publica.storm.s3.proto.User.GeoIPOrBuilder getLocationOrBuilder() {
      if (locationBuilder_ != null) {
        return locationBuilder_.getMessageOrBuilder();
      } else {
        return location_ == null ?
            com.publica.storm.s3.proto.User.GeoIP.getDefaultInstance() : location_;
      }
    }
    /**
     * <code>optional .logger.User.GeoIP location = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.publica.storm.s3.proto.User.GeoIP, com.publica.storm.s3.proto.User.GeoIP.Builder, com.publica.storm.s3.proto.User.GeoIPOrBuilder> 
        getLocationFieldBuilder() {
      if (locationBuilder_ == null) {
        locationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.publica.storm.s3.proto.User.GeoIP, com.publica.storm.s3.proto.User.GeoIP.Builder, com.publica.storm.s3.proto.User.GeoIPOrBuilder>(
                getLocation(),
                getParentForChildren(),
                isClean());
        location_ = null;
      }
      return locationBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:logger.User)
  }

  // @@protoc_insertion_point(class_scope:logger.User)
  private static final com.publica.storm.s3.proto.User DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.publica.storm.s3.proto.User();
  }

  public static com.publica.storm.s3.proto.User getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User>
      PARSER = new com.google.protobuf.AbstractParser<User>() {
    public User parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<User> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<User> getParserForType() {
    return PARSER;
  }

  public com.publica.storm.s3.proto.User getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

